# Generated by Django 6.1.1 on 2026-09-18 20:47

import core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated searchable tags.', max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('service_area', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('areas_served', models.CharField(blank=True, max_length=300)),
                ('website_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('google_business_url', models.URLField(blank=True)),
                ('google_place_identifier', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, upload_to=core.models.vendor_upload_path, validators=[core.models.validate_vendor_image])),
                ('logo', models.ImageField(blank=True, upload_to=core.models.vendor_upload_path, validators=[core.models.validate_vendor_image])),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('business_name',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.vendor_upload_path, validators=[core.models.validate_vendor_image])),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='core.vendorprofile')),
            ],
            options={
                'ordering': ('display_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('SERVICE', 'Service'), ('PACKAGE', 'Package'), ('RENTAL', 'Rental'), ('PRODUCT', 'Product')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=core.models.vendor_upload_path, validators=[core.models.validate_vendor_image])),
                ('description', models.TextField()),
                ('pricing_type', models.CharField(choices=[('FIXED', 'Fixed'), ('STARTING_FROM', 'Starting from'), ('HOURLY', 'Hourly'), ('CONTACT_FOR_QUOTE', 'Contact for quote')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.vendorprofile')),
            ],
            options={
                'ordering': ('-is_active', 'title'),
            },
        ),
    ]
