# Generated by Django 6.1.1 on 2026-09-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='logo',
            new_name='profile_image',
        ),
    ]
