# Generated by Django 6.1.1 on 2026-09-18 22:37

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def migrate_text_categories(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    VendorProfile = apps.get_model("core", "VendorProfile")
    Listing = apps.get_model("core", "Listing")

    def get_category(name):
        if not name:
            return None
        category, _ = Category.objects.get_or_create(name=name, defaults={"slug": slugify(name)})
        return category

    for profile in VendorProfile.objects.exclude(category=""):
        category = get_category(profile.category)
        if category:
            profile.primary_category_id = category.pk
            profile.save(update_fields=["primary_category"])

    for listing in Listing.objects.exclude(legacy_category=""):
        category = get_category(listing.legacy_category)
        if category:
            listing.category_id = category.pk
            listing.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_logo_vendorprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, related_name='additional_profiles', to='core.category'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_profiles', to='core.category'),
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='legacy_category',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='core.category'),
        ),
        migrations.RunPython(migrate_text_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='legacy_category',
        ),
    ]
