# Generated by Django 6.1.1 on 2026-09-18 23:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vendorprofile_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, choices=[('WEDDING', 'Wedding'), ('BIRTHDAY', 'Birthday'), ('CORPORATE', 'Corporate event'), ('BABY_SHOWER', 'Baby shower'), ('ANNIVERSARY', 'Anniversary'), ('OTHER', 'Something else')], max_length=30)),
                ('custom_event_type', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('guest_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('help_types', models.JSONField(blank=True, default=list)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('colours', models.JSONField(blank=True, default=list)),
                ('venue_type', models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('UNDECIDED', 'Undecided')], default='UNDECIDED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('completed_step', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to=settings.AUTH_USER_MODEL)),
                ('required_categories', models.ManyToManyField(blank=True, related_name='event_requests', to='core.category')),
                ('saved_vendors', models.ManyToManyField(blank=True, related_name='saved_for_events', to='core.vendorprofile')),
            ],
            options={
                'ordering': ('-updated_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('budget_min__isnull', True), ('budget_max__isnull', True), ('budget_max__gte', models.F('budget_min')), _connector='OR'), name='event_budget_order'), models.CheckConstraint(condition=models.Q(('completed_step__lte', 6)), name='event_progress_range'), models.CheckConstraint(condition=models.Q(('guest_count__isnull', True), ('guest_count__gte', 1), _connector='OR'), name='event_positive_guests')],
            },
        ),
    ]
