# Generated by Django 6.1.1 on 2026-09-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vendorprofile_is_active_eventrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='availability',
            field=models.TextField(blank=True, help_text='Describe current availability, lead times, or seasonal limits.'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
