# Generated by Django 6.1.1 on 2026-09-19 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendorprofile_availability_vendorprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='help_types',
            field=models.JSONField(blank=True, default=list, help_text='Event services this listing provides.'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=2000)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_note', models.TextField(blank=True, help_text='Staff evidence confirming the customer used this vendor. Never public.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.eventrequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.vendorprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'vendor'), name='one_review_per_event_vendor'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range')],
            },
        ),
    ]
