# Generated by Django 6.1.1 on 2026-09-20 19:45

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_listing_help_types_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_address',
            field=models.CharField(blank=True, help_text='Private: never displayed on your public profile.', max_length=300),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='experience_answer',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='max_travel_distance',
            field=models.CharField(blank=True, choices=[('', 'Select travel distance'), ('LOCAL', 'Local only'), ('25', '25 km'), ('50', '50 km'), ('100', '100 km'), ('250', '250 km'), ('ANY', 'Open to travel')], max_length=10),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='price_range',
            field=models.CharField(blank=True, choices=[('', 'Select price range'), ('BUDGET', 'Budget'), ('MID', 'Mid-range'), ('PREMIUM', 'Premium'), ('LUXURY', 'Luxury')], max_length=10),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='review_feedback',
            field=models.TextField(blank=True, help_text='Feedback visible to the vendor.'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='services_answer',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='specialties_answer',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='style_answer',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pricing_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('STARTING_FROM', 'Starting from'), ('HOURLY', 'Per hour'), ('PER_PERSON', 'Per person'), ('PER_ITEM', 'Per item'), ('CONTACT_FOR_QUOTE', 'Contact for quote')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes requested')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.vendor_upload_path, validators=[core.models.validate_vendor_image])),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.listing')),
            ],
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='service_locations',
            field=models.ManyToManyField(blank=True, to='core.servicelocation'),
        ),
        migrations.CreateModel(
            name='VendorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('SERVICE', 'Service'), ('EVENT', 'Event type')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('name', 'kind'), name='unique_vendor_tag')],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='service_tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'kind': 'SERVICE'}, to='core.vendortag'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='event_tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'kind': 'EVENT'}, related_name='event_profiles', to='core.vendortag'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='service_tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'kind': 'SERVICE'}, related_name='service_profiles', to='core.vendortag'),
        ),
    ]
