# Generated by Django 6.1.1 on 2026-09-26 03:00

from django.db import migrations, models


CATALOGUE = (
    ("Event Planning", "event-planning", "PLANNING", ["EVENT_PLANNER", "EVENT_COORDINATOR", "FULL_PLANNING", "PLANNER", "PARTIAL_PLANNING", "COMPLETE_SERVICE"], True),
    ("Full planning", "full-planning", "PLANNING", ["FULL_PLANNING", "EVENT_PLANNER"], False),
    ("Partial planning", "partial-planning", "PLANNING", ["PARTIAL_PLANNING", "EVENT_PLANNER"], False),
    ("Day-of coordination", "day-of-coordination", "PLANNING", ["EVENT_COORDINATOR", "PARTIAL_PLANNING"], False),
    ("Backdrops", "backdrops", "DECOR", ["DECORATOR"], True),
    ("Table styling", "table-styling", "DECOR", ["DECORATOR"], False),
    ("Signage", "signage", "DECOR", ["DECORATOR"], False),
    ("Themed setups", "themed-setups", "DECOR", ["DECORATOR"], False),
    ("Bouquets", "bouquets", "FLORALS", ["FLORIST"], True),
    ("Centrepieces", "centrepieces", "FLORALS", ["FLORIST"], False),
    ("Floral arches", "floral-arches", "FLORALS", ["FLORIST"], False),
    ("Balloon garlands", "balloon-garlands", "BALLOONS", ["BALLOON_ARTIST"], True),
    ("Balloon arches", "balloon-arches", "BALLOONS", ["BALLOON_ARTIST"], False),
    ("Balloon bouquets", "balloon-bouquets", "BALLOONS", ["BALLOON_ARTIST"], False),
    ("Bridal makeup", "bridal-makeup", "BEAUTY", ["MAKEUP_ARTIST"], True),
    ("Guest makeup", "guest-makeup", "BEAUTY", ["MAKEUP_ARTIST"], False),
    ("Hairstyling", "hairstyling", "BEAUTY", ["HAIRSTYLIST"], False),
    ("Buffet", "buffet", "FOOD", ["CATERER", "CATERING"], True),
    ("Plated meals", "plated-meals", "FOOD", ["CATERER", "CATERING"], False),
    ("Private dining", "private-dining", "FOOD", ["PRIVATE_CHEF", "CATERING"], False),
    ("Dessert tables", "dessert-tables", "FOOD", ["CAKE_DESSERTS", "CATERING"], False),
    ("Event coverage", "event-coverage", "PHOTO_VIDEO", ["PHOTOGRAPHER", "VIDEOGRAPHER"], True),
    ("Portraits", "portraits", "PHOTO_VIDEO", ["PHOTOGRAPHER"], False),
    ("Photo booths", "photo-booths", "PHOTO_VIDEO", ["PHOTOGRAPHER", "ENTERTAINMENT"], False),
    ("DJs", "djs", "ENTERTAINMENT", ["ENTERTAINMENT"], True),
    ("Live music", "live-music", "ENTERTAINMENT", ["ENTERTAINMENT"], False),
    ("MCs", "mcs", "ENTERTAINMENT", ["ENTERTAINMENT"], False),
    ("Magicians", "magicians", "ENTERTAINMENT", ["ENTERTAINMENT", "KIDS_ENTERTAINMENT"], False),
    ("Face painting", "face-painting", "ENTERTAINMENT", ["KIDS_ENTERTAINMENT"], False),
    ("Tables", "tables", "RENTALS", ["RENTAL_ITEMS", "RENTALS"], True),
    ("Chairs", "chairs", "RENTALS", ["RENTAL_ITEMS", "RENTALS"], False),
    ("Linens", "linens", "RENTALS", ["RENTAL_ITEMS", "RENTALS"], False),
    ("Tableware", "tableware", "RENTALS", ["RENTAL_ITEMS", "RENTALS"], False),
    ("Props", "props", "RENTALS", ["RENTAL_ITEMS", "RENTALS"], False),
    ("Lighting", "lighting", "RENTALS", ["RENTAL_ITEMS", "RENTALS"], False),
    ("Sound", "sound", "RENTALS", ["RENTAL_ITEMS", "RENTALS"], False),
    ("Delivery", "delivery", "LOGISTICS", ["DELIVERY_PICKUP"], True),
    ("Pickup", "pickup", "LOGISTICS", ["DELIVERY_PICKUP"], False),
    ("Setup", "setup", "LOGISTICS", ["SETUP_TEARDOWN"], False),
    ("Teardown", "teardown", "LOGISTICS", ["SETUP_TEARDOWN"], False),
)


def seed_catalogue(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    database = schema_editor.connection.alias
    for name, slug, group, help_types, featured in CATALOGUE:
        category = Category.objects.using(database).filter(slug=slug).first()
        if category is None:
            category = Category.objects.using(database).filter(name=name).first()
        if category is None:
            Category.objects.using(database).create(
                name=name, slug=slug, service_group=group,
                relevant_help_types=help_types, is_featured=featured,
            )
            continue
        category.service_group = group
        category.relevant_help_types = help_types
        category.is_featured = featured
        category.save(update_fields=("service_group", "relevant_help_types", "is_featured"), using=database)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_normalize_event_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='relevant_help_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='service_group',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('DECOR', 'Decor'), ('FLORALS', 'Florals'), ('BALLOONS', 'Balloons'), ('BEAUTY', 'Beauty'), ('FOOD', 'Food'), ('PHOTO_VIDEO', 'Photography / video'), ('ENTERTAINMENT', 'Entertainment'), ('RENTALS', 'Rentals'), ('LOGISTICS', 'Logistics'), ('OTHER', 'Other services')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='other_help_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RunPython(seed_catalogue, migrations.RunPython.noop),
    ]
