# Generated by Django 6.1.1 on 2026-09-28 02:18

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_is_featured_category_relevant_help_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='other_services',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='VendorOnboardingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to=core.models.vendor_upload_path, validators=[core.models.validate_vendor_image])),
                ('cover', models.ImageField(blank=True, upload_to=core.models.vendor_upload_path, validators=[core.models.validate_vendor_image])),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listing')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_draft', to='core.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VendorDraftPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.vendor_upload_path, validators=[core.models.validate_vendor_image])),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.vendoronboardingdraft')),
            ],
        ),
    ]
